topological_nav:
  topological_nav_node:
    ros__parameters:
      points:
        - "wp0"
        - "0.23"
        - "0.0"
        - "1.0"
        - "0.0"

        - "wp1"
        - "1.14"
        - "2.32"
        - "1.0"
        - "0.0"

        - "wp2" 
        - "0.55"
        - "5.61"
        - "0.35"
        - "1.0"

        - "wp3"
        - "6.39"
        - "3.26"
        - "0.43"
        - "0.9"
